collage_maker/urls.py
from django.urls import path
from . import views

app_name = "collage_maker"

urlpatterns = [
    path("", views.index, name="index"),
]

connect_four/urls.py
from django.urls import path
from . import views

app_name = "connect_four"

urlpatterns = [
    path("", views.index, name="index"),
]

home/urls.py
from django.urls import path
from .import views

app_name = "home"

urlpatterns = [
    path("", views.index, name="index"),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path("todo/", include("todo.urls")),
    path("qr/", include("qr_code_generator.urls")),
]

qr_code_generator/urls.py
from django.urls import path
from . import views

app_name = "qr"

urlpatterns = [
    path("", views.index, name="index"),
    path("generate/", views.generate_qr_code, name="generate"),
]

todo/urls.py
from django.urls import path

from . import views

app_name = "todo"
urlpatterns = [
    path("", views.index, name="index"),
    path("remove/<int:todo_id>/", views.remove, name="remove"),
    path("update/<int:todo_id>/", views.update, name="update"),
]

collage_maker/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.db import models

# Create your models here.


class Todo(models.Model):
    todo_text = models.CharField(max_length=250)
    is_done = models.IntegerField(default=0)
    date_created = models.DateTimeField("Date Created")

    def __str__(self):
        return self.todo_text

todo/forms.py
from django import forms


class TodoForm(forms.Form):
    text = forms.CharField(max_length=250, label="")

collage_maker/views.py
from django.shortcuts import render


# Create your views here.


def index(request):
    return render(request, "collage_maker/index-1.html")

connect_four/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request, "connect_four/index.html")

home/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.


def index(request):
    return render(request, "home/index.html")

qr_code_generator/views.py
from django.shortcuts import render

from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse

import segno
import json
import os
import base64
# Create your views here.


def index(request):
    return render(request, "qr/index.html")


# path = os.getcwd()
# parent_dir = os.path.abspath(os.path.join(path, os.pardir))
# qr_dir = os.path.join(parent_dir, "qr_code_generator/static/qr/images/")


os.chdir("./qr_code_generator/static/qr/images/")


def generate_qr_code(request):

    if request.method == "POST":
        data = request.body
        data = json.loads(data)

        qr_code = segno.make_qr(data["text"])
        qr_code.save(
            "qr.png",
            scale=10,
            border=5,
        )

        response = {}
        with open("qr.png", "rb") as image:
            img = image.read()
            response['qr'] = base64.encodebytes(img).decode('utf-8')
            image.close()

        # os.remove("qr.png")

        print("-"*30)
        print("Qr Code Generated")
        print("-"*30)

    return JsonResponse(response, safe=False)

todo/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.http import HttpResponseRedirect

from django.urls import reverse

from .models import Todo
from .forms import TodoForm

import json

# Create your views here.


def index(request):
    todo = Todo.objects.all().order_by('-date_created')
    context = {
        "todo": todo,
        "form": TodoForm(),
    }

    if request.method == "POST":
        form = TodoForm(request.POST)

        if form.is_valid():
            text = form.cleaned_data["text"]
            is_done = 0
            date_created = timezone.now()

            todo = Todo(todo_text=text, is_done=is_done,
                        date_created=date_created)
            todo.save()

    return render(request, "todo/index.html", context)


def update(request, todo_id):
    print("-"*30)
    todo = get_object_or_404(Todo, id=todo_id)
    if request.method == "POST":
        data = request.body
        data = json.loads(data)

        todo.is_done = data["is_done"]
        todo.todo_text = data["todo_text"]
        todo.save()
        print(f"Todo: {todo_id} updated...")

    print("-"*30)

    return HttpResponseRedirect(reverse("todo:index"))


def remove(request, todo_id):
    print("-"*30)
    todo = get_object_or_404(Todo, id=todo_id)
    todo.delete()
    print(f"Todo: {todo_id} deleted...")

    print("-"*30)

    return HttpResponseRedirect(reverse("todo:index"))

collage_maker/templates/collage_maker/index-1.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Collage Maker</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% load static %}
  <link href="{% static 'collage_maker/style.css' %}" rel="stylesheet">

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
</head>

<body>
  <header>
    <h1>Collage Maker</h1>
  </header>
  <div class="container">
      <div class="sidebar">
        <h1>Choose a collage</h1>
        <div id="collage-icon-container"></div>

        <h1>Background color</h1>
        <div id="color-list"></div>
        <input id="input-custom-color" type="text" placeholder="custom color ex: #FFFFFF" />
      </div>

      <div id="collage-container"></div>

      
  </div>

</body>
<script type="module" src="{% static 'collage_maker/script.js' %}"></script>

</html>

collage_maker/templates/collage_maker/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Collage Maker</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% load static %}
  <link href="{% static 'collage_maker/style.css' %}" rel="stylesheet">
</head>

<body>
  <header>
    <h1>Collage Maker</h1>
  </header>
  <div class="collage">
    <div class="collage-header">
    </div>
    <div class="collage-body">
        <img id="btn-prev" src="{% static 'collage_maker/images/left-arrow.png' %}"/>
        <div id="container-1"></div>
        <div id="container-2"></div>
        <div id="container-3"></div>

        <img id="btn-next" src="{% static 'collage_maker/images/right-arrow.png' %}"/>
    </div>
  </div>

</body>
<script type="module" src="{% static 'collage_maker/script.js' %}"></script>

</html>

connect_four/templates/connect_four/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Connect Four</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% load static %}
  <link href="{% static 'connect_four/style.css' %}" rel="stylesheet">
  <link rel="shortcut icon" href="{%  static 'connect_four/images/favicon.ico' %}">

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Pixelify+Sans:wght@400..700&display=swap" rel="stylesheet">
</head>

<body>
  <div class="header">
    <div>
      <h1 class="turn" id="turn">Turn: Yellow</h1>
      <div class="score">
        <h3 class="score_player_1" id="score_player_1">Yellow: 0</h3>
        <h3 class="score_player_2" id="score_player_2">Red: 0</h3>
      </div>

    </div>
    <!-- <img id="reset_btn" class="reset_btn" src="{% static 'connect_four/images/reset.png' %}" /> -->
      <h3 class="reset_btn" id="reset_btn">Reset</h3>
  </div>
  <div id="container" class="container"></div>

  </div>

</body>

<script src="{% static 'connect_four/script.js' %}"></script>

</html>

home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Kyle Pagayon</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% load static %}
  <link href="{% static 'home/style.css' %}" rel="stylesheet">

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Pixelify+Sans:wght@400..700&display=swap" rel="stylesheet">
</head>



<body>
  <header>
    <a href="{% url 'home:index' %}">Kyle Pagayon</a>

    <div class="navigation">
      <a class="projects" href="#project-section" style="hover:background-color:#FF8CB2">Projects</a>
      <a class="technologies" href="#technologies-section">Technologies</a>
      <a class="socials" href="#socials-section">Socials</a>
      <a class="about" href="#about-section">About Me</a>
    </div>
  </header>

  <section class="introduction" id="introduction">
    <h1>Hi I'm Kyle Pagayon</h1>
    <h2>Welcome to my Portfolio</h2>

    <div class="navigation">
      <a href="#project-section" style="background-color:#FF8CB2;">Projects</a>
      <a href="#technologies-section" style="background-color:#BAD368;">Technologies</a>
      <a href="#socials-section" style="background-color:#4697E8;">Socials</a>
      <a href="#about-section" style="background-color:#FE8B81;">About Me</a>
    </div>

    <div class="peroro">
      <img src="{% static 'home/images/peroro.png' %}" />
    </div>
  </section>


  <section class="project-section" id="project-section">
    <h2>My Project's</h2>
    <div class="project-container">
      <div class="project">
        <a href="{% url 'todo:index' %}" target=”_blank”>
          Todo App
          <img src="{% static 'home/images/todo-app.png' %}" />
        </a>
      </div>
      <div class="project">
        <a href="{% url 'todo:index' %}" target=”_blank”>
          Todo App
          <img src="{% static 'home/images/todo-app.png' %}" />
        </a>
      </div>

      <div class="project">
        <a href="{% url 'qr:index' %}" target=”_blank”>
          QR Code Generator

          <img src="{% static 'home/images/qr-code-generator.png' %}" />
        </a>
      </div>
    </div>
  </section>


  <section class="technologies-section" id="technologies-section">
    <h2>Technologies</h2>

    <div class="container">
      <div class="technologies-icon">

        <h1>Front-End</h1>
        <div class="front-end">
          <div>
            <h2>HTML</h2>
            <img src="{% static 'home/images/html.png' %}" />
          </div>

          <div>
            <h2>CSS</h2>
            <img src="{% static 'home/images/css-3.png' %}" />
          </div>

          <div>
            <h2>JAVASCRIPT</h2>
            <img src="{% static 'home/images/js.png' %}" />
          </div>
        </div>

        <h1>Back-End</h1>
        <div class="front-end">
          <div>
            <h2>PYTHON</h2>
            <img src="{% static 'home/images/python.png' %}" />
          </div>

          <div>
            <h2>MYSQL</h2>
            <img src="{% static 'home/images/sql-server.png' %}" />
          </div>
        </div>

      </div>
      <div class="">
        <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
          dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
          commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat
          nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim
          id est laborum."</p>

      </div>
    </div>

  </section>

  <section class="socials-section" id="socials-section">
    <h2>Socials</h2>

    <div class="container">
      <div class="social-icons">
        <div>
          <img src="{% static 'home/images/gmail.png' %}" />
          <span id="email">kylepagayon58@gmail.com</span>
          <img class="copy" src="{% static 'home/images/copy.png' %}" onclick='clipboard("email")' />
        </div>

        <div>
          <img src="{% static 'home/images/facebook.png' %}" />
          <a id="facebook"
            target="_blank"
            href="https://www.facebook.com/kylepagayon.pagayon">https://www.facebook.com/kylepagayon.pagayon</a>
          <img class="copy" src="{% static 'home/images/copy.png' %}" onclick='clipboard("facebook")' />
        </div>

        <div>
          <img src="{% static 'home/images/github.png' %}" />
          <a id="github" target="_blank" href="https://github.com/toki-04">https://github.com/toki-04</a>
          <img class="copy" src="{% static 'home/images/copy.png' %}" onclick='clipboard("github")' />
        </div>
      </div>

      <div class="speech-bubble">
        <h3>Send me a message!</h3>

      </div>
      <div>

  </section>

  <section class="about-section" id="about-section">
    <h2>About Me</h2>

    <div class="container">
        <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
          dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
          commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat
          nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim
          id est laborum."</p>

        <img src="{% static 'home/images/complete.png' %}" />

    </div>
  </section>

</body>

<script src="{% static 'home/script.js' %}"></script>

</html>

home/templates/home/snow.html
<style>
  /* customizable snowflake styling */

  .snowflake {

    color: #fff;

    font-size: 1em;

    font-family: Arial, sans-serif;

    text-shadow: 0 0 5px #000;

  }



  .snowflake,
  .snowflake .inner {
    animation-iteration-count: infinite;
    animation-play-state: running
  }

  @keyframes snowflakes-fall {
    0% {
      transform: translateY(0)
    }

    100% {
      transform: translateY(110vh)
    }
  }

  @keyframes snowflakes-shake {

    0%,
    100% {
      transform: translateX(0)
    }

    50% {
      transform: translateX(80px)
    }
  }

  .snowflake {
    position: fixed;
    top: -10%;
    z-index: 9999;
    -webkit-user-select: none;
    user-select: none;
    cursor: default;
    animation-name: snowflakes-shake;
    animation-duration: 3s;
    animation-timing-function: ease-in-out
  }

  .snowflake .inner {
    animation-duration: 10s;
    animation-name: snowflakes-fall;
    animation-timing-function: linear
  }

  .snowflake:nth-of-type(0) {
    left: 1%;
    animation-delay: 0s
  }

  .snowflake:nth-of-type(0) .inner {
    animation-delay: 0s
  }

  .snowflake:first-of-type {
    left: 10%;
    animation-delay: 1s
  }

  .snowflake:first-of-type .inner,
  .snowflake:nth-of-type(8) .inner {
    animation-delay: 1s
  }

  .snowflake:nth-of-type(2) {
    left: 20%;
    animation-delay: .5s
  }

  .snowflake:nth-of-type(2) .inner,
  .snowflake:nth-of-type(6) .inner {
    animation-delay: 6s
  }

  .snowflake:nth-of-type(3) {
    left: 30%;
    animation-delay: 2s
  }

  .snowflake:nth-of-type(11) .inner,
  .snowflake:nth-of-type(3) .inner {
    animation-delay: 4s
  }

  .snowflake:nth-of-type(4) {
    left: 40%;
    animation-delay: 2s
  }

  .snowflake:nth-of-type(10) .inner,
  .snowflake:nth-of-type(4) .inner {
    animation-delay: 2s
  }

  .snowflake:nth-of-type(5) {
    left: 50%;
    animation-delay: 3s
  }

  .snowflake:nth-of-type(5) .inner {
    animation-delay: 8s
  }

  .snowflake:nth-of-type(6) {
    left: 60%;
    animation-delay: 2s
  }

  .snowflake:nth-of-type(7) {
    left: 70%;
    animation-delay: 1s
  }

  .snowflake:nth-of-type(7) .inner {
    animation-delay: 2.5s
  }

  .snowflake:nth-of-type(8) {
    left: 80%;
    animation-delay: 0s
  }

  .snowflake:nth-of-type(9) {
    left: 90%;
    animation-delay: 1.5s
  }

  .snowflake:nth-of-type(9) .inner {
    animation-delay: 3s
  }

  .snowflake:nth-of-type(10) {
    left: 25%;
    animation-delay: 0s
  }

  .snowflake:nth-of-type(11) {
    left: 65%;
    animation-delay: 2.5s
  }
</style>

<div class="snowflakes" aria-hidden="true">

  <div class="snowflake">

    <div class="inner">❅</div>

  </div>

  <div class="snowflake">

    <div class="inner">❅</div>

  </div>

  <div class="snowflake">

    <div class="inner">❅</div>

  </div>

  <div class="snowflake">

    <div class="inner">❅</div>

  </div>

  <div class="snowflake">

    <div class="inner">❅</div>

  </div>

  <div class="snowflake">

    <div class="inner">❅</div>

  </div>

  <div class="snowflake">

    <div class="inner">❅</div>

  </div>

  <div class="snowflake">

    <div class="inner">❅</div>

  </div>

  <div class="snowflake">

    <div class="inner">❅</div>

  </div>

  <div class="snowflake">

    <div class="inner">❅</div>

  </div>

  <div class="snowflake">

    <div class="inner">❅</div>

  </div>

  <div class="snowflake">

    <div class="inner">❅</div>

  </div>

</div>

qr_code_generator/templates/qr/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Qr Code Generator</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% load static %}
  <link href="{% static 'qr/style.css' %}" rel="stylesheet">
  <link rel="shortcut icon" href="{%  static 'qr/images/favicon.ico' %}">

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">
</head>

<body>
  <h1 class="title">Qr Code Generator</h1>
  <div class="qr">
    <div class="qr-body">
        <div class="icons">
          <div>
              <img src="{% static 'qr/images/url.png' %}" /><span>URL</span>
          </div>
          <div>
              <img src="{% static 'qr/images/wifi.png' %}" /><span>WIFI</span>
          </div>
          <div>
              <img src="{% static 'qr/images/txt.png' %}" /><span>TXT</span>
          </div>
        </div>
        <textarea class="qr-text" id="qr-text"></textarea>
        <button
          class="qr-btn"
          onclick='generate_qr_code(`{% url "qr:generate" %}`)'>
          GENERATE QR CODE
        </button>
    </div>

    <div class="qr-settings" id="qr-settings">
        <h3>QR CODE GENERATED</h3>
        <img id="qr-code" class="qr-code"/>
        <button class="qr-btn"><a  href="{% static 'qr/images/qr.png' %}" download>DOWNLOAD QR CODE</a></button>
    </div>
  </div>



</body>
  <script src="{% static 'qr/script.js' %}"></script>

</html>

todo/templates/todo/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Todo App</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  {% load static %}
  <link rel="stylesheet" href="{% static 'todo/style.css' %}">
  <link rel="shortcut icon" href="{%  static 'todo/images/favicon.ico' %}">

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">

</head>

<body>
  <!-- <h1 class="title">TODO APP</h1> -->

  <div class="todo-counter">
      <img src="{% static 'todo/images/peroro-arona.png' %}" />
      <div class="bubble">
          <img src="{% static 'todo/images/bubble.png' %}" />
          <span class="counter" id="counter">0</span>
      </div>
  </div>

  <form action="" method="post">
    {% csrf_token %}
      <div class="text-form">{{form}}</div>
      <button class="submit" type="submit">
        <img src="{% static 'todo/images/add.png' %}"/>
      </button>

  </form>

  <div class="todos">
  {% for item in todo %}
  <div class="todo-container" id=todo_container_{{forloop.counter}}>
    {% if item.is_done %}
    <input
          type="checkbox"
          id=checkbox_{{forloop.counter}}
          onclick='update_todo(`todo_container_{{forloop.counter}}`, "{% url 'todo:update' item.id%}");'
          checked
        >


    {% else %}

    <input
          type="checkbox"
          id=checkbox_{{forloop.counter}}
          onclick='update_todo(`todo_container_{{forloop.counter}}`, "{% url 'todo:update' item.id%}");'>

    {% endif %}

        <textarea
          class="text"
          id=`text_{{forloop.counter}}`
          rows="1"
          cols="1"
          spellcheck="false"
          onchange='update_todo(`todo_container_{{forloop.counter}}`, "{% url 'todo:update' item.id%}");'>{{item.todo_text}}</textarea>
        <button 
          class="remove"
          onclick='remove_todo(
            `todo_container_{{forloop.counter}}`,
            `item.id`,
            "{% url 'todo:remove' item.id %}",
          )'>
            <img src="{% static '/todo/images/close.png' %}" />
        </button>
  </div>
  {% endfor %}
  </div>
</body>


<script src="{% static 'todo/script.js' %}"></script>

</html>